import { chromium, request } from '@playwright/test';
const ctx = await request.newContext({ignoreHTTPSErrors:true});
const lr = await ctx.post('https://admin.104.248.132.130.sslip.io/api/admin/v1/auth/login',{data:{email:'admin@rampa.ua',password:'${YMS_ADMIN_PASSWORD}'}});
const tok = (await lr.json()).accessToken;
const r = await ctx.get('https://admin.104.248.132.130.sslip.io/api/admin/v1/stores?city=%D0%9A%D0%B8%D1%97%D0%B2&perPage=100&page=2',{headers:{Authorization:'Bearer '+tok}});
const j = await r.json();
const last = j.items[j.items.length-1];
console.log('київських усього:', j.total, '| контрольна філія:', last.externalId, '—', last.address);

const b = await chromium.launch();
const p = await b.newPage({ ignoreHTTPSErrors: true, locale: 'uk-UA' });
await p.goto('https://admin.104.248.132.130.sslip.io/');
await p.waitForSelector('input[type=password]');
await p.fill('#email','admin@rampa.ua'); await p.fill('#password','${YMS_ADMIN_PASSWORD}');
await Promise.all([p.waitForResponse(r=>r.url().includes('/auth/login')), p.click('button[type=submit]')]);
await p.goto('https://admin.104.248.132.130.sslip.io/suppliers/41ebd3dd-4435-4b80-a9f8-b7ae6d154b95');
await p.waitForLoadState('networkidle');
await p.click('button:has-text("Магазини")');
await p.waitForTimeout(3500);
await p.click('button:has-text("+8")').catch(()=>{});
await p.waitForTimeout(1000);
const s = await p.$('input[type=search][placeholder="Пошук"]');
await s.fill(last.externalId);
await p.waitForTimeout(1500);
const opts = await p.$$eval('[role=option], li, label', els=>els.map(e=>e.innerText.trim()).filter(t=>/^\d{3,}/.test(t)));
console.log('знайдено за кодом', last.externalId+':', opts.length, '→', opts.slice(0,2));
await b.close();
